# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            OpenSRE
tagline:          'A collection of DevOps tools'
description:      'OpenSRE is a plaeholder name for a project that centers around Open Source DevOps tools, with an emphasis on Sources of Truth, and Truth management.'
url:              http://opensre.github.io
paginate:         5

author:
  name:           'Dale Hamel'
  url:            https://github.com/dalehamel

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/OpenSRE/OpenSRE.github.io
